function P = RandomProtein(n)
% 随机产生一个含有n个氨基酸的蛋白质链
% P是一个长度为3n的字符串,可用于蛋白质编码

% 由61种可能出现的氨基酸组成的串(不包括结束密码子)
ListOfAA= ['GCTGCCGCAGCG'...
           'CGTCGCCGACGGAGAAGG'...
           'AATAAC'...
           'GATGAC'...
           'TGTTGC'...
           'CAACAG'...
           'GAAGAG'...
           'GGTGGCGGAGGG'...
           'CATCAC'...
           'ATTATCATA'...
           'CTTCTCCTACTGTTATTG'...
           'AAAAAG'...
           'ATG'...
           'TTTTTC'...
           'CCTCCCCCACCG'...
           'TCTTCCTCATCGAGTAGC'...
           'ACTACCACAACG'...
           'TGG'...
           'TATTAC'...
           'GTTGTCGTAGTG'];
P= '';
for  k= 1:n
    % 随机产生下一个氨基酸
    j= ceil(61*rand(1));
    nextAA= ListOfAA(3*(j-1)+1:3*j);
    P= [P nextAA];
end  % for结束


end
% RandomProtein函数结束